"""add bill model

Revision ID: af5767b466ab
Revises: a1b2c3d4e5f6
Create Date: 2026-06-30 05:20:30.305640

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "af5767b466ab"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("amount_estimated", sa.Float(), nullable=True),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column("due_day", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_variable", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bills_id"), "bills", ["id"], unique=False)
    op.drop_index(op.f("ix_merchants_user_id"), table_name="merchants")
    op.create_index(op.f("ix_merchants_id"), "merchants", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_merchants_id"), table_name="merchants")
    op.create_index(op.f("ix_merchants_user_id"), "merchants", ["user_id"], unique=False)
    op.drop_index(op.f("ix_bills_id"), table_name="bills")
    op.drop_table("bills")
    # ### end Alembic commands ###
