"""add transaction fields

Revision ID: f4a3a875e97d
Revises: 033dadf9a9bc
Create Date: 2026-06-29 02:35:51.191722

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f4a3a875e97d"
down_revision = "033dadf9a9bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("merchant_id", sa.Integer(), nullable=True))
    op.add_column("transactions", sa.Column("bill_id", sa.Integer(), nullable=True))
    op.add_column("transactions", sa.Column("goal_id", sa.Integer(), nullable=True))
    op.add_column(
        "transactions",
        sa.Column("is_pending", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    op.add_column(
        "transactions",
        sa.Column("is_recurring", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "is_recurring")
    op.drop_column("transactions", "is_pending")
    op.drop_column("transactions", "goal_id")
    op.drop_column("transactions", "bill_id")
    op.drop_column("transactions", "merchant_id")
    # ### end Alembic commands ###
